
-- suppression des index sur les colonnes utilisees comme cles etrangeres
DROP INDEX art_activite_art_agglomeration_id_index;
DROP INDEX art_agglomeration_art_type_agglomeration_id_index;
DROP INDEX art_debarquement_art_agglomeration_id_index;
DROP INDEX art_engin_activite_art_activite_id_index;
DROP INDEX art_engin_peche_art_debarquement_id_index ;
DROP INDEX art_fraction_art_debarquement_id_index;
DROP INDEX art_lieu_de_peche_ref_secteur_id_index;
DROP INDEX art_poisson_mesure_art_fraction_id_index;
DROP INDEX art_type_engin_art_grand_type_engin_id_index;
DROP INDEX art_unite_peche_art_agglomeration_id_index;
DROP INDEX exp_biologie_exp_fraction_id_index;
DROP INDEX exp_campagne_ref_systeme_id_index;
DROP INDEX exp_coup_peche_exp_campagne_id_index;
DROP INDEX exp_environnement_exp_force_courant_id_index;
DROP INDEX exp_fraction_exp_coup_peche_id_index;
DROP INDEX exp_station_exp_debris_id_index;
DROP INDEX exp_trophique_exp_biologie_id_index;
DROP INDEX ref_espece_ref_categorie_ecologique_id_index;
DROP INDEX ref_famille_ref_ordre_id_index;
DROP INDEX ref_secteur_ref_systeme_id_index;
DROP INDEX ref_systeme_ref_pays_id_index;