<?php
//*****************************************
// stat_definition_globvar_position.inc
//*****************************************
// Created by Yann Laurent
// 2010-02-23 : creation
//*****************************************
// Ce fichier contient une serie de definition de position pour des calculs complementaires de stats
// et pour gerer le stockage des variables complémentaires....
//*****************************************
global $posGenEcoIDasp ;
global $posGenEcolibIDasp ;
global $posGenTroIDasp ;
global $posGenTrolibIDasp ;
global $posGenfamlibIDasp ;

global $posGenEcoIDats ;
global $posGenEcolibIDats;
global $posGenTroIDats ;
global $posGenTrolibIDats ;
global $posGenfamlibIDats ;

global $posGenEcoIDattgt;
global $posGenEcolibIDattgt;
global $posGenTroIDattgt;
global $posGenTrolibIDattgt;
global $posGenfamlibIDattgt;

global $posGenEcoIDatgts;
global $posGenEcolibIDatgts;
global $posGenTroIDatgts;
global $posGenTrolibIDatgts;
global $posGenfamlibIDatgts;

global $posSomNbenqueteast ;
global $posValMinast ;
global $posValMaxast ;

global $posSomNbenqueteasp ;
global $posValMinasp ;
global $posValMaxasp ;

global $posSomNbenqueteats ;
global $posValMinats ;
global $posValMaxats ;

global $posSomNbenqueteasgt ;
global $posValMinasgt ;
global $posValMaxasgt ;

global $posSomNbenqueteattgt ;
global $posValMinattgt ;
global $posValMaxattgt ;

global $posSomNbenqueteatgts ;
global $posValMinatgts ;
global $posValMaxatgts ;
?>
