<?php 
// NavbarCR.inc : Créé le 22/10/2008 par Yann Laurent, contient les entêtes des menus ouvrable ainsi que le contenu

//echo"<div class=\"marginCR\">Compte Rendu&nbsp;<a id=\"v_slidein".$navbarLevel."\" href=\"#\"> Afficher </a>|<a 
//id=\"v_slideout".$navbarLevel."\" href=\"#\"> Fermer </a>| <strong>status</strong>: <span id=\"vertical_status".$navbarLevel."\">open
//</span></div>";
echo"<div id=\"vertical_slide".$navbarLevel."\">".$texteDiv."</div>";



?>