SELECT pg_catalog.setval('art_activite_id_seq', 208267, true);
SELECT pg_catalog.setval('art_debarquement_id_seq',78443, true);
SELECT pg_catalog.setval('art_engin_activite_id_seq',239706 , true);
SELECT pg_catalog.setval('art_engin_peche_id_seq',104576, true);
SELECT pg_catalog.setval('art_lieu_de_peche_id_seq', 1406, true);
SELECT pg_catalog.setval('art_poisson_mesure_id_seq',1567681, true);
SELECT pg_catalog.setval('art_unite_peche_id_seq',15768, true);
SELECT pg_catalog.setval('exp_campagne_id_seq',193 , true);
SELECT pg_catalog.setval('exp_cp_peche_id_seq',4662, true);
SELECT pg_catalog.setval('exp_contenu_biologie_id_seq',6515,true);
