<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<meta name="robots" content="index,follow" />
<meta name="description" content="ppeao" />
<meta name="keywords" content="otolithe otolithe.com olivier roux yann laurent" />
<meta name="keywords" content="ird ppeao" />
<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
<link rel="icon" type="image/x-icon" href="/favicon.ico" />

<link href="/styles/mainstyles.css" title="mainstyles" rel="stylesheet" type="text/css" />
<script src="/js/basic.js" type="text/javascript" charset="utf-8"></script>


